###
#   Database Settings###
##   H2 Settings, web interface, local
# По умолчанию закрытие последнего соединения с базой данных закрывает базу данных. Д
#ля базы данных в памяти это означает потерю содержимого. 
#Чтобы база данных оставалась открытой, добавьте ;DB_CLOSE_DELAY=-1к URL-адресу базы данных. 
#Чтобы сохранить содержимое базы данных в памяти, пока виртуальная машина работает, 
#используйте jdbc:h2:mem:test;DB_CLOSE_DELAY=-1. 
   # url: jdbc:h2://mem:db;DB_CLOSE_DELAY=-1;
#### Возможно необходимо выбрать embedded в консоли, уже после get запроса
 При проблемах подключения в Database plugin from IDEA, необходимо параметр OLD_INFORMATION_SCHEMA=TRUE this 
<a href="https://github.com/JetBrains/jetbrains_guide/issues/215">info</a>

<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <scope>runtime</scope>
</dependency> 
###
spring:

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#   jdbc:h2:file:C:/Users/${spring.nameUser}/h2
    url: jdbc:h2:file:~/test 
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
